routes/web.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/beatmapsets/{beatmapset}/covers', 'BeatmapsetsController@covers')->name('beatmapsets.covers');
    Route::post('/beatmapsets/{beatmapset}/covers/regenerate', 'BeatmapsetsController@regenerateCovers')->name('beatmapsets.covers.regenerate');
    Route::resource('beatmapsets', 'BeatmapsetsController', ['only' => ['show']]);

    Route::resource('beatmapset-discussions', 'BeatmapsetDiscussionsController', ['only' => ['store']]);

    Route::post('contests/{id}/zip', 'ContestsController@gimmeZip')->name('contests.get-zip');
    Route::resource('contests', 'ContestsController', ['only' => ['index', 'show']]);

    Route::resource('logs', 'LogsController', ['only' => ['index']]);

    Route::get('/', 'PagesController@root')->name('root');

    Route::group(['as' => 'forum.', 'prefix' => 'forum', 'namespace' => 'Forum'], function () {
        Route::resource('forum-covers', 'ForumCoversController', ['only' => ['index', 'store', 'update']]);
    });

    Route::group(['as' => 'store.', 'prefix' => 'store', 'namespace' => 'Store'], function () {
        Route::resource('addresses', 'AddressesController', ['only' => ['update']]);

        Route::post('orders/ship', 'OrdersController@ship')->name('orders.ship');
        Route::resource('orders', 'OrdersController', ['only' => ['index', 'show', 'update']]);

        Route::resource('orders.items', 'OrderItemsController', ['only' => ['update']]);

        Route::get('/', function () {
            return ujs_redirect(route('admin.store.orders.index'));
        });
    });
});

Route::group(['prefix' => 'beatmaps'], function () {
    // featured artists
    Route::resource('artists', 'ArtistsController', ['only' => ['index', 'show']]);
});
Route::get('beatmaps/{beatmap}/scores', 'BeatmapsController@scores')->name('beatmaps.scores');
Route::resource('beatmaps', 'BeatmapsController', ['only' => ['show']]);

Route::group(['prefix' => 'beatmapsets'], function () {
    Route::put('beatmap-discussions/{beatmap_discussion}/vote', 'BeatmapDiscussionsController@vote')->name('beatmap-discussions.vote');
    Route::post('beatmap-discussions/{beatmap_discussion}/restore', 'BeatmapDiscussionsController@restore')->name('beatmap-discussions.restore');
    Route::post('beatmap-discussions/{beatmap_discussion}/deny-kudosu', 'BeatmapDiscussionsController@denyKudosu')->name('beatmap-discussions.deny-kudosu');
    Route::post('beatmap-discussions/{beatmap_discussion}/allow-kudosu', 'BeatmapDiscussionsController@allowKudosu')->name('beatmap-discussions.allow-kudosu');
    Route::resource('beatmap-discussions', 'BeatmapDiscussionsController', ['only' => ['destroy', 'show']]);

    Route::post('beatmap-discussions-posts/{beatmap_discussion_post}/restore', 'BeatmapDiscussionPostsController@restore')->name('beatmap-discussion-posts.restore');
    Route::resource('beatmap-discussion-posts', 'BeatmapDiscussionPostsController', ['only' => ['destroy', 'store', 'update']]);
});
Route::get('beatmapsets/search/{filters?}', 'BeatmapsetsController@search')->name('beatmapsets.search');
Route::get('beatmapsets/{beatmapset}/discussion', 'BeatmapsetsController@discussion')->name('beatmapsets.discussion');
Route::put('beatmapsets/{beatmapset}/nominate', 'BeatmapsetsController@nominate')->name('beatmapsets.nominate');
Route::put('beatmapsets/{beatmapset}/disqualify', 'BeatmapsetsController@disqualify')->name('beatmapsets.disqualify');
Route::post('beatmapsets/{beatmapset}/update-favourite', 'BeatmapsetsController@updateFavourite')->name('beatmapsets.update-favourite');
Route::resource('beatmapsets', 'BeatmapsetsController', ['only' => ['index', 'show']]);

Route::group(['prefix' => 'community'], function () {
    Route::get('chat', 'CommunityController@getChat')->name('chat');

    Route::resource('contests', 'ContestsController', ['only' => ['index', 'show']]);

    Route::put('contest-entries/{contest_entry}/vote', 'ContestEntriesController@vote')->name('contest-entries.vote');
    Route::resource('contest-entries', 'ContestEntriesController', ['only' => ['store', 'destroy']]);

    Route::post('livestreams/promote', 'LivestreamsController@promote')->name('livestreams.promote');
    Route::resource('livestreams', 'LivestreamsController', ['only' => ['index']]);

    Route::get('matches/{match}/history', 'MatchesController@history')->name('matches.history');
    Route::resource('matches', 'MatchesController', ['only' => ['show']]);

    Route::post('tournaments/{tournament}/unregister', 'TournamentsController@unregister')->name('tournaments.unregister');
    Route::post('tournaments/{tournament}/register', 'TournamentsController@register')->name('tournaments.register');
    Route::resource('tournaments', 'TournamentsController');

    Route::get('profile/{id}', function ($id) {
        return ujs_redirect(route('users.show', $id));
    });

    Route::group(['as' => 'forum.', 'namespace' => 'Forum'], function () {
        Route::group(['prefix' => 'forums'], function () {
            Route::resource('forum-covers', 'ForumCoversController', ['only' => ['store', 'update', 'destroy']]);

            Route::get('posts/{post}/raw', 'PostsController@raw')->name('posts.raw');
            Route::post('posts/{post}/restore', 'PostsController@restore')->name('posts.restore');
            Route::resource('posts', 'PostsController', ['only' => ['destroy', 'edit', 'show', 'update']]);

            Route::post('topics/preview', 'TopicsController@preview')->name('topics.preview');
            Route::post('topics/{topic}/issue-tag', 'TopicsController@issueTag')->name('topics.issue-tag');
            Route::post('topics/{topic}/lock', 'TopicsController@lock')->name('topics.lock');
            Route::post('topics/{topic}/move', 'TopicsController@move')->name('topics.move');
            Route::post('topics/{topic}/pin', 'TopicsController@pin')->name('topics.pin');
            Route::post('topics/{topic}/reply', 'TopicsController@reply')->name('topics.reply');
            Route::post('topics/{topic}/vote', 'TopicsController@vote')->name('topics.vote');
            Route::post('topics/{topic}/vote-feature', 'TopicsController@voteFeature')->name('topics.vote-feature');
            Route::post('topics/{topic}/watch', 'TopicsController@watch')->name('topics.watch');
            Route::resource('topics', 'TopicsController', ['only' => ['create', 'show', 'store', 'update']]);

            Route::resource('topic-covers', 'TopicCoversController', ['only' => ['store', 'update', 'destroy']]);

            Route::resource('topic-watches', 'TopicWatchesController', ['only' => ['index']]);
        });

        Route::get('forums/search', 'ForumsController@search')->name('forums.search');
        Route::resource('forums', 'ForumsController', ['only' => ['index', 'show']]);
    });
});

Route::group(['prefix' => 'home'], function () {
    Route::get('account/edit', 'AccountController@edit')->name('account.edit');
    // Uploading file doesn't quite work with PUT/PATCH.
    // Reference: https://bugs.php.net/bug.php?id=55815
    // Note that hhvm behaves differently (the same as POST).
    Route::post('account/avatar', 'AccountController@avatar')->name('account.avatar');
    Route::post('account/cover', 'AccountController@cover')->name('account.cover');
    Route::put('account/email', 'AccountController@updateEmail')->name('account.email');
    Route::put('account/page', 'AccountController@updatePage')->name('account.page');
    Route::put('account/password', 'AccountController@updatePassword')->name('account.password');
    Route::post('account/reissue-code', 'AccountController@reissueCode')->name('account.reissue-code');
    Route::post('account/verify', 'AccountController@verify')->name('account.verify');
    Route::put('account', 'AccountController@update')->name('account.update');

    Route::get('search', 'HomeController@search')->name('search');
    Route::get('quick-search', 'HomeController@quickSearch')->name('quick-search');
    Route::post('bbcode-preview', 'HomeController@bbcodePreview')->name('bbcode-preview');
    Route::get('changelog', 'HomeController@getChangelog')->name('changelog');
    Route::get('download', 'HomeController@getDownload')->name('download');
    Route::get('icons', 'HomeController@getIcons');
    Route::post('set-locale', 'HomeController@setLocale')->name('set-locale');
    Route::get('support', 'HomeController@supportTheGame')->name('support-the-game');

    Route::delete('password-reset', 'PasswordResetController@destroy');
    Route::get('password-reset', 'PasswordResetController@index')->name('password-reset');
    Route::post('password-reset', 'PasswordResetController@create');
    Route::put('password-reset', 'PasswordResetController@update');

    Route::resource('news', 'NewsController', ['except' => ['destroy']]);
});

Route::get('legal/{page}', 'LegalController@show')->name('legal');

// ranking section
Route::get('/rankings/{mode?}', function ($mode = 'osu') {
    if (!array_key_exists($mode, App\Models\Beatmap::MODES)) {
        abort(404);
    }

app/Models/Forum/AuthOption.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace App\Models\Forum;

class AuthOption extends Model
{
    protected $table = 'phpbb_acl_options';

    protected $primaryKey = 'auth_option_id';
    public $timestamps = false;

    protected $guarded = [];
}

app/Http/Controllers/Admin/Forum/ForumCoversController.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace App\Http\Controllers\Admin\Forum;

use App\Http\Controllers\Admin\Controller;
use App\Models\Forum\Forum;
use App\Models\Forum\ForumCover;
use Auth;
use Request;

class ForumCoversController extends Controller
{
    protected $section = 'admin-forum';
    protected $actionPrefix = 'forum-covers-';
    private $params = [];

    public function index()
    {
        $forums = Forum::with('cover')->get();

        return view('admin.forum.forum_covers.index', compact('forums'));
    }

    public function store()
    {
        if (($this->coverParams()['forum_id'] ?? null) === null) {
            abort(422);
        }

        $cover = ForumCover::firstOrCreate(['forum_id' => $this->coverParams()['forum_id']]);

        $cover->update($this->coverParams());

        return redirect(route('admin.forum.forum-covers.index').'#forum-'.$cover->forum_id);
    }

    public function update($id)
    {
        $cover = ForumCover::findOrFail($id);

        $cover->update($this->coverParams());

        return redirect(route('admin.forum.forum-covers.index').'#forum-'.$cover->forum_id);
    }

    private function coverParams()
    {
        if (isset($this->params['cover']) === false) {
            $this->params['cover'] = get_params(Request::all(), 'forum_cover', [
                'forum_id:int',

                'main_cover.cover_file:file',
                'main_cover._delete:bool',

                'default_topic_cover.cover_file:file',
                'default_topic_cover._delete:bool',
            ]);
            $this->params['cover']['user_id'] = Auth::user()->user_id;
        }

        return $this->params['cover'];
    }
}

app/Http/Controllers/Forum/Controller.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace App\Http\Controllers\Forum;

use App\Http\Controllers\Controller as BaseController;
use App\Models\Log;

abstract class Controller extends BaseController
{
    public function logModerate($operation, $data, $object)
    {
        $this->log([
            'log_type' => Log::LOG_FORUM_MOD,
            'log_operation' => $operation,
            'log_data' => $data,

            'topic_id' => $object->topic_id,
            'forum_id' => $object->forum_id,
        ]);
    }
}

app/Http/Controllers/Forum/ForumCoversController.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace App\Http\Controllers\Forum;

use App\Exceptions\ImageProcessorException;
use App\Models\Forum\Forum;
use App\Models\Forum\ForumCover;
use App\Transformers\Forum\ForumCoverTransformer;
use Auth;
use Request;

class ForumCoversController extends Controller
{
    protected $section = 'community';

    public function __construct()
    {
        parent::__construct();

        view()->share('current_action', 'forum-forum-covers-'.current_action());

        $this->middleware('auth', ['only' => [
            'destroy',
            'store',
            'update',
        ]]);

        $this->middleware(function ($request, $next) {
            if (Auth::check() && !Auth::user()->isAdmin()) {
                abort(403);
            }

            return $next($request);
        });
    }

    public function store()
    {
        if (Request::hasFile('cover_file') !== true) {
            abort(422);
        }

        $forum = Forum::findOrFail(Request::input('forum_id'));

        if ($forum->cover !== null) {
            abort(422);
        }

        try {
            $cover = ForumCover::upload(
                Request::file('cover_file')->getRealPath(),
                Auth::user(),
                $forum
            );
        } catch (ImageProcessorException $e) {
            return error_popup($e->getMessage());
        }

        return json_item($cover, new ForumCoverTransformer());
    }

    public function destroy($id)
    {
        $cover = ForumCover::find($id);

        if ($cover !== null) {
            $cover->deleteWithFile();
        }

        return json_item($cover, new ForumCoverTransformer());
    }

    public function update($id)
    {
        $cover = ForumCover::findOrFail($id);

        if (Request::hasFile('cover_file') === true) {
            try {
                $cover = $cover->updateFile(
                    Request::file('cover_file')->getRealPath(),
                    Auth::user()
                );
            } catch (ImageProcessorException $e) {
                return error_popup($e->getMessage());
            }
        }

        return json_item($cover, new ForumCoverTransformer());
    }
}

resources/views/forum/topics/_header.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
<?php
    $headerCover = $cover['fileUrl'] ?? $cover['defaultFileUrl'] ?? null;
    $newTopic = !isset($topic);
?>
<div class="osu-page">
    @include('forum._header_breadcrumb', [
        'forum' => $forum ?? $topic->forum,
    ])

    <div
        class="forum-category-header
            forum-category-header--topic
            {{ $newTopic ?
                'forum-category-header--topic-create'
                : 'u-forum--topic-cover'
            }}
            js-forum-cover--header
            js-header--main"
        style="{{ $headerCover !== null ? "background-image: url('{$headerCover}');" : '' }}"
    >
        <div class="forum-category-header__loading js-forum-cover--loading">
            @include('objects._spinner')
        </div>

        <div class="forum-category-header__titles">
            @if ($newTopic)
                <input
                    class="forum-category-header__title js-form-placeholder-hide"
                    required
                    tabindex="1"
                    name="title"
                    type="text"
                    value="{{ Request::old("title") }}"
                    placeholder="{{ trans("forum.topic.create.placeholder.title") }}"
                />
            @else
                <h1 class="forum-category-header__title">
                    <a href="{{ route("forum.topics.show", $topic->topic_id) }}" class="link--white link--no-underline">
                        {{ $topic->topic_title }}
                    </a>
                </h1>
            @endif

            <div class="forum-category-header__counters">
                <div class="forum-category-header__counter">
                    @include('forum.topics._header_total_counter')
                </div>

                @if(!$newTopic && priv_check('ForumTopicModerate', $topic)->can())
                    <div class="forum-category-header__counter">
                        @include('forum.topics._header_deleted_counter')
                    </div>
                @endif
            </div>
        </div>

        @if ($newTopic || priv_check('ForumTopicEdit', $topic)->can())
            <div class="forum-category-header__actions">
                @include('forum._cover_editor')
            </div>
        @endif
    </div>

    @if (!$newTopic)
        <div class="forum-topic-header__sticky-marker js-sticky-header" data-sticky-header-target="forum-topic-headernav"></div>
    @endif
</div>

resources/views/forum/topics/_issue_tag_added.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
@include('forum.topics._issue_tag', [
    'issueTag' => 'added',
])

resources/views/forum/topics/_issue_tag_assigned.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
@include('forum.topics._issue_tag', [
    'issueTag' => 'assigned',
])

resources/views/forum/topics/_issue_tag_invalid.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
@include('forum.topics._issue_tag', [
    'issueTag' => 'invalid',
])

resources/views/forum/topics/_poll.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
{!! Form::open([
    'route' => ['forum.topics.vote', $topic->topic_id],
    'method' => 'POST',
    'data-remote' => true,
    'data-checkbox-validation' => json_encode([
        'forum_topic_vote[option_ids][]' => [
            'min' => 1,
            'max' => $topic->poll_max_options,
        ],
    ]),
    'class' => 'forum-poll js-checkbox-validation',
]) !!}
    <h2 class="forum-poll__row forum-poll__row--title">
        {!! $topic->pollTitleHTML() !!}
    </h2>

    <table class="forum-poll__row forum-poll__row--options">
        <tbody>
            @foreach ($pollSummary['options'] as $pollOptionId => $pollOption)
                @include('forum.topics._poll_row', compact($pollOptionId, $pollOption, $pollSummary))
            @endforeach
        </tbody>
    </table>

    <div class="forum-poll__row forum-poll__row--details">
        <div class="forum-poll__detail">
            {{ trans('forum.topics.show.poll.detail.total', ['count' => $pollSummary['total']]) }}
        </div>

        @if ($topic->pollEnd() !== null)
            <div class="forum-poll__detail forum-poll__detail--sub">
                @if ($topic->pollEnd()->isFuture())
                    {{ trans('forum.topics.show.poll.detail.end_time', ['time' => $topic->pollEnd()]) }}
                @else
                    {{ trans('forum.topics.show.poll.detail.ended', ['time' => $topic->pollEnd()]) }}
                @endif
            </div>
        @endif
    </div>

    <div class="forum-poll__row">
        @if (!priv_check('ForumTopicVote', $topic)->can())
            {{ priv_check('ForumTopicVote', $topic)->message() }}
        @else
            <button class="btn-osu-lite btn-osu-lite--default js-checkbox-validation--submit">
                {{ trans('forum.topics.show.poll.vote') }}
            </button>
        @endif
    </div>
{!! Form::close() !!}

resources/views/forum/topics/_post_box_footer.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
<?php
    if (!isset($editing)) { $editing = false; }
?>
<div class="post-box__toolbar hidden-xs">
    @include("forum._post_toolbar")
</div>

<div class="post-editor__actions">
    <button class="js-editor-zoom--visible js-editor-zoom--end hidden btn-osu btn-osu--small btn-osu-default post-editor__action post-editor__action--compact" type="button" title="{{ trans("forum.topic.post_edit.zoom.end") }}">
        <i class="fa fa-compress"></i>
    </button>

    <div class="visible-xs">
        <button class="js-editor-zoom--hidden js-editor-zoom--start btn-osu btn-osu--small btn-osu-default post-editor__action post-editor__action--compact" type="button" title="{{ trans("forum.topic.post_edit.zoom.start") }}">
            <i class="fa fa-expand"></i>
        </button>
    </div>

    @if ($editing)
        <button class="js-editor-zoom--hidden btn-osu btn-osu--small btn-osu-default js-edit-post-cancel post-editor__action" type="button">{{ trans("forum.topic.post_edit.cancel") }}</button>
    @endif

    <button class="js-editor-zoom--hidden btn-osu btn-osu--small btn-osu-default post-editor__action" type="submit">{{ $submitText }}</button>
</div>

resources/views/forum/topics/_watch.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
<a
    class="btn-circle btn-circle--topic-nav js-forum-topic-watch"
    href="{{ route('forum.topics.watch', [
        $topic,
        'watch' => !$state,
    ]) }}"
    data-remote="1"
    data-method="post"
    data-topic-id="{{ $topic->topic_id }}"
    title="{{ trans('forum.topics.watch.watch-'.(int) !$state) }}"
>
    @if ($state)
        <i class="fa fa-eye-slash"></i>
    @else
        <i class="fa fa-eye"></i>
    @endif
</a>