routes/web.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/beatmapsets/{beatmapset}/covers', 'BeatmapsetsController@covers')->name('beatmapsets.covers');
    Route::post('/beatmapsets/{beatmapset}/covers/regenerate', 'BeatmapsetsController@regenerateCovers')->name('beatmapsets.covers.regenerate');
    Route::resource('beatmapsets', 'BeatmapsetsController', ['only' => ['show']]);

    Route::resource('beatmapset-discussions', 'BeatmapsetDiscussionsController', ['only' => ['store']]);

    Route::post('contests/{id}/zip', 'ContestsController@gimmeZip')->name('contests.get-zip');
    Route::resource('contests', 'ContestsController', ['only' => ['index', 'show']]);

    Route::resource('logs', 'LogsController', ['only' => ['index']]);

    Route::get('/', 'PagesController@root')->name('root');

    Route::group(['as' => 'forum.', 'prefix' => 'forum', 'namespace' => 'Forum'], function () {
        Route::resource('forum-covers', 'ForumCoversController', ['only' => ['index', 'store', 'update']]);
    });

    Route::group(['as' => 'store.', 'prefix' => 'store', 'namespace' => 'Store'], function () {
        Route::resource('addresses', 'AddressesController', ['only' => ['update']]);

        Route::post('orders/ship', 'OrdersController@ship')->name('orders.ship');
        Route::resource('orders', 'OrdersController', ['only' => ['index', 'show', 'update']]);

        Route::resource('orders.items', 'OrderItemsController', ['only' => ['update']]);

        Route::get('/', function () {
            return ujs_redirect(route('admin.store.orders.index'));
        });
    });
});

Route::group(['prefix' => 'beatmaps'], function () {
    // featured artists
    Route::resource('artists', 'ArtistsController', ['only' => ['index', 'show']]);
});
Route::get('beatmaps/{beatmap}/scores', 'BeatmapsController@scores')->name('beatmaps.scores');
Route::resource('beatmaps', 'BeatmapsController', ['only' => ['show']]);

Route::group(['prefix' => 'beatmapsets'], function () {
    Route::put('beatmap-discussions/{beatmap_discussion}/vote', 'BeatmapDiscussionsController@vote')->name('beatmap-discussions.vote');
    Route::post('beatmap-discussions/{beatmap_discussion}/restore', 'BeatmapDiscussionsController@restore')->name('beatmap-discussions.restore');
    Route::post('beatmap-discussions/{beatmap_discussion}/deny-kudosu', 'BeatmapDiscussionsController@denyKudosu')->name('beatmap-discussions.deny-kudosu');
    Route::post('beatmap-discussions/{beatmap_discussion}/allow-kudosu', 'BeatmapDiscussionsController@allowKudosu')->name('beatmap-discussions.allow-kudosu');
    Route::resource('beatmap-discussions', 'BeatmapDiscussionsController', ['only' => ['destroy', 'show']]);

    Route::post('beatmap-discussions-posts/{beatmap_discussion_post}/restore', 'BeatmapDiscussionPostsController@restore')->name('beatmap-discussion-posts.restore');
    Route::resource('beatmap-discussion-posts', 'BeatmapDiscussionPostsController', ['only' => ['destroy', 'store', 'update']]);
});
Route::get('beatmapsets/search/{filters?}', 'BeatmapsetsController@search')->name('beatmapsets.search');
Route::get('beatmapsets/{beatmapset}/discussion', 'BeatmapsetsController@discussion')->name('beatmapsets.discussion');
Route::put('beatmapsets/{beatmapset}/nominate', 'BeatmapsetsController@nominate')->name('beatmapsets.nominate');
Route::put('beatmapsets/{beatmapset}/disqualify', 'BeatmapsetsController@disqualify')->name('beatmapsets.disqualify');
Route::post('beatmapsets/{beatmapset}/update-favourite', 'BeatmapsetsController@updateFavourite')->name('beatmapsets.update-favourite');
Route::resource('beatmapsets', 'BeatmapsetsController', ['only' => ['index', 'show']]);

Route::group(['prefix' => 'community'], function () {
    Route::get('chat', 'CommunityController@getChat')->name('chat');

    Route::resource('contests', 'ContestsController', ['only' => ['index', 'show']]);

    Route::put('contest-entries/{contest_entry}/vote', 'ContestEntriesController@vote')->name('contest-entries.vote');
    Route::resource('contest-entries', 'ContestEntriesController', ['only' => ['store', 'destroy']]);

    Route::post('livestreams/promote', 'LivestreamsController@promote')->name('livestreams.promote');
    Route::resource('livestreams', 'LivestreamsController', ['only' => ['index']]);

    Route::get('matches/{match}/history', 'MatchesController@history')->name('matches.history');
    Route::resource('matches', 'MatchesController', ['only' => ['show']]);

    Route::post('tournaments/{tournament}/unregister', 'TournamentsController@unregister')->name('tournaments.unregister');
    Route::post('tournaments/{tournament}/register', 'TournamentsController@register')->name('tournaments.register');
    Route::resource('tournaments', 'TournamentsController');

    Route::get('profile/{id}', function ($id) {
        return ujs_redirect(route('users.show', $id));
    });

    Route::group(['as' => 'forum.', 'namespace' => 'Forum'], function () {
        Route::group(['prefix' => 'forums'], function () {
            Route::resource('forum-covers', 'ForumCoversController', ['only' => ['store', 'update', 'destroy']]);

            Route::get('posts/{post}/raw', 'PostsController@raw')->name('posts.raw');
            Route::post('posts/{post}/restore', 'PostsController@restore')->name('posts.restore');
            Route::resource('posts', 'PostsController', ['only' => ['destroy', 'edit', 'show', 'update']]);

            Route::post('topics/preview', 'TopicsController@preview')->name('topics.preview');
            Route::post('topics/{topic}/issue-tag', 'TopicsController@issueTag')->name('topics.issue-tag');
            Route::post('topics/{topic}/lock', 'TopicsController@lock')->name('topics.lock');
            Route::post('topics/{topic}/move', 'TopicsController@move')->name('topics.move');
            Route::post('topics/{topic}/pin', 'TopicsController@pin')->name('topics.pin');
            Route::post('topics/{topic}/reply', 'TopicsController@reply')->name('topics.reply');
            Route::post('topics/{topic}/vote', 'TopicsController@vote')->name('topics.vote');
            Route::post('topics/{topic}/vote-feature', 'TopicsController@voteFeature')->name('topics.vote-feature');
            Route::post('topics/{topic}/watch', 'TopicsController@watch')->name('topics.watch');
            Route::resource('topics', 'TopicsController', ['only' => ['create', 'show', 'store', 'update']]);

            Route::resource('topic-covers', 'TopicCoversController', ['only' => ['store', 'update', 'destroy']]);

            Route::resource('topic-watches', 'TopicWatchesController', ['only' => ['index']]);
        });

        Route::get('forums/search', 'ForumsController@search')->name('forums.search');
        Route::resource('forums', 'ForumsController', ['only' => ['index', 'show']]);
    });
});

Route::group(['prefix' => 'home'], function () {
    Route::get('account/edit', 'AccountController@edit')->name('account.edit');
    // Uploading file doesn't quite work with PUT/PATCH.
    // Reference: https://bugs.php.net/bug.php?id=55815
    // Note that hhvm behaves differently (the same as POST).
    Route::post('account/avatar', 'AccountController@avatar')->name('account.avatar');
    Route::post('account/cover', 'AccountController@cover')->name('account.cover');
    Route::put('account/email', 'AccountController@updateEmail')->name('account.email');
    Route::put('account/page', 'AccountController@updatePage')->name('account.page');
    Route::put('account/password', 'AccountController@updatePassword')->name('account.password');
    Route::post('account/reissue-code', 'AccountController@reissueCode')->name('account.reissue-code');
    Route::post('account/verify', 'AccountController@verify')->name('account.verify');
    Route::put('account', 'AccountController@update')->name('account.update');

    Route::get('search', 'HomeController@search')->name('search');
    Route::get('quick-search', 'HomeController@quickSearch')->name('quick-search');
    Route::post('bbcode-preview', 'HomeController@bbcodePreview')->name('bbcode-preview');
    Route::get('changelog', 'HomeController@getChangelog')->name('changelog');
    Route::get('download', 'HomeController@getDownload')->name('download');
    Route::get('icons', 'HomeController@getIcons');
    Route::post('set-locale', 'HomeController@setLocale')->name('set-locale');
    Route::get('support', 'HomeController@supportTheGame')->name('support-the-game');

    Route::delete('password-reset', 'PasswordResetController@destroy');
    Route::get('password-reset', 'PasswordResetController@index')->name('password-reset');
    Route::post('password-reset', 'PasswordResetController@create');
    Route::put('password-reset', 'PasswordResetController@update');

    Route::resource('news', 'NewsController', ['except' => ['destroy']]);
});

Route::get('legal/{page}', 'LegalController@show')->name('legal');

// ranking section
Route::get('/rankings/{mode?}', function ($mode = 'osu') {
    if (!array_key_exists($mode, App\Models\Beatmap::MODES)) {
        abort(404);
    }

app/Http/Controllers/API/BeatmapsetsController.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace App\Http\Controllers\API;

use App\Transformers\BeatmapsetTransformer;
use Auth;

class BeatmapsetsController extends Controller
{
    public function favourites()
    {
        $favourites = Auth::user()->favouriteBeatmapsets();

        return json_collection(
            $favourites->get(),
            new BeatmapsetTransformer()
        );
    }
}

app/Http/Controllers/Admin/BeatmapsetsController.php
<?php

/**
 *    Copyright 2015-2017 ppy Pty. Ltd.
 *
 *    This file is part of osu!web. osu!web is distributed with the hope of
 *    attracting more community contributions to the core ecosystem of osu!.
 *
 *    osu!web is free software: you can redistribute it and/or modify
 *    it under the terms of the Affero GNU General Public License version 3
 *    as published by the Free Software Foundation.
 *
 *    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
 *    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *    See the GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace App\Http\Controllers\Admin;

use App\Jobs\RegenerateBeatmapsetCover;
use App\Models\Beatmapset;

class BeatmapsetsController extends Controller
{
    protected $section = 'admin.beatmapsets';

    public function covers($id)
    {
        $beatmapset = Beatmapset::findOrFail($id);

        return view('admin.beatmapsets.cover', compact('beatmapset'));
    }

    public function regenerateCovers($id)
    {
        $beatmapset = Beatmapset::findOrFail($id);

        $job = (new RegenerateBeatmapsetCover($beatmapset))->onQueue('beatmap_processor');
        $this->dispatch($job);

        return back();
    }

    public function show($id)
    {
        $beatmapset = Beatmapset::findOrFail($id);

        return view('admin.beatmapsets.show', compact('beatmapset'));
    }
}

resources/views/admin/beatmapsets/cover.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
@extends('master')

@section('content')
    <div class="osu-layout__row osu-layout__row--page">
        <h2>{{$beatmapset->title}} - {{$beatmapset->artist}}</h2>
        <br>
        {!! Form::open([
            'route' => ['admin.beatmapsets.covers.regenerate', $beatmapset->beatmapset_id],
            'method' => 'POST'
        ]) !!}
            <button>regenerate</button>
        {!! Form::close() !!}
        @foreach ($beatmapset->coverSizes() as $size)
            <h3>{{$size}}</h3>
            <p>{{$beatmapset->coverURL($size)}}</p>
            <img src="{{$beatmapset->coverURL($size)}}">
            <br>
        @endforeach
    </div>
@endsection

resources/views/admin/beatmapsets/show.blade.php
{{--
    Copyright 2015-2017 ppy Pty. Ltd.

    This file is part of osu!web. osu!web is distributed with the hope of
    attracting more community contributions to the core ecosystem of osu!.

    osu!web is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License version 3
    as published by the Free Software Foundation.

    osu!web is distributed WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with osu!web.  If not, see <http://www.gnu.org/licenses/>.
--}}
@extends('master')

@section('content')
    <div class="osu-layout__row osu-layout__row--page">
        <h1>{{ $beatmapset->title }} - {{ $beatmapset->artist }}</h1>

        <ul>
            <li>{{ trans('admin.beatmapsets.show.discussion._') }}:
                @if ($beatmapset->beatmapsetDiscussion !== null)
                    {{ trans('admin.beatmapsets.show.discussion.active') }}
                @else
                    {{ trans('admin.beatmapsets.show.discussion.inactive') }}
                    /
                    <a
                        href="{{ route('admin.beatmapset-discussions.store', ['beatmapset_id' => $beatmapset->beatmapset_id]) }}"
                        data-method="POST"
                        data-confirm="{{ trans('admin.beatmapsets.show.discussion.activate_confirm') }}"
                    >{{ trans('admin.beatmapsets.show.discussion.activate') }}</a>
                @endif
            </li>
        </ul>
    </div>
@endsection